NationalDysphagiaCareGuid/Controllers/FormController.cs
using Microsoft.AspNetCore.Mvc;
using NationalDysphagiaCareGuid.Models;
using System.Net.Mail;
using System.Net;

namespace NationalDysphagiaCareGuid.Controllers
{
    public class FormController : Controller
    {
        private readonly NationalDysphagiaCareGuidDbContext _context;

        public FormController(NationalDysphagiaCareGuidDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult PostFormSubmission([FromBody]int id)
        {
            PatientsController patients=new PatientsController(_context);
            var patient = patients.GetPatient(id);

            try
            {
                if (patient.IsCompletedSuccessfully && patient.Result.Value != null)
                {
                    SendEmail(patient.Result.Value);
                }

                return Json(new { Status = true });
            }
            catch (Exception ex)
            {
                return Json(new { Status = false, ex.Message });
            }
        }

        private bool SendEmail(Patient patient)
        {
            try
            {
                var smtpClient = new SmtpClient("smtp.gmail.com")
                {
                    Port = 587,
                    Credentials = new NetworkCredential("28a.v10@gmail.com", "ekzuwuhthgkhrmbz"),
                    EnableSsl = true,
                };

                string convertToYesNo(int value)
                {
                    return value == 1 ? "YES" : "NO";
                }

                var mailMessage = new MailMessage
                {
                    From = new MailAddress("28a.v10@gmail.com"),
                    Subject = $"Nation Dysphagia Connecting Guide - New Patient Form - {patient.FirstName} {patient.LastName} (Patient ID: {patient.PatientId})",
                    Body = $@"<!DOCTYPE html>
                    <html lang=\""en\"">
                       <head>
                          <meta charset=\""UTF-8\"">
                          <meta name=\""viewport\"" content=\""width=device-width,initial-scale=1\"">
                          <title>Patient Details</title>
                          <style>body{{font-family:Arial,sans-serif;line-height:1.6;margin:0;padding:20px}}table{{width:100%;border-collapse:collapse;margin-bottom:20px}}td,th{{border:1px solid #ddd;padding:8px;text-align:left}}th{{background-color:#f2f2f2}}h2{{color:#333}}</style>
                       </head>
                       <body>
                          <h2>Patient Details</h2>
                          <p>Dear [Recipient's Name],</p>
                          <p>Here are the details of the patient you requested:</p>
                          <table>
                             <tr>
                                <th>Attribute</th>
                                <th>Details</th>
                             </tr>
                             <tr>
                                <td>Patient ID</td>
                                <td>{patient.PatientId}</td>
                             </tr>
                             <tr>
                                <td>First Name</td>
                                <td>{patient.FirstName}</td>
                             </tr>
                             <tr>
                                <td>Last Name</td>
                                <td>{patient.LastName}</td>
                             </tr>
                             <tr>
                                <td>Gender</td>
                                <td>{patient.Gender}</td>
                             </tr>
                             <tr>
                                <td>Age</td>
                                <td>{patient.Age}</td>
                             </tr>
                             <tr>
                                <td>Email</td>
                                <td>{patient.Email}</td>
                             </tr>
                             <tr>
                                <td>Phone Number</td>
                                <td>{patient.PhoneNumber}</td>
                             </tr>
                          </table>
                          <h3>Patient History:</h3>
                          <table>
                             <tr>
                                <th>Attribute</th>
                                <th>Details</th>
                             </tr>
                             <tr>
                                <td>Dysphagia</td>
                                <td>{convertToYesNo(patient.PatientHistories.First().Dysphagia)}</td>
                             </tr>
                             <tr>
                                <td>Respiratory Issue</td>
                                <td>{convertToYesNo(patient.PatientHistories.First().RespiratoryIssue)}</td>
                             </tr>
                             <tr>
                                <td>Stroke</td>
                                <td>{convertToYesNo(patient.PatientHistories.First().Stroke)}</td>
                             </tr>
                             <tr>
                                <td>Cancer</td>
                                <td>{convertToYesNo(patient.PatientHistories.First().Cancer)}</td>
                             </tr>
                             <tr>
                                <td>Gastrological Issue</td>
                                <td>{convertToYesNo(patient.PatientHistories.First().GastrologicalIssue)}</td>
                             </tr>
                             <tr>
                                <td>Surgeries in Past</td>
                                <td>{convertToYesNo(patient.PatientHistories.First().SurgeriesInPast)}</td>
                             </tr>
                             <tr>
                                <td>Feeding Mode</td>
                                <td>{patient.PatientHistories.First().FeedingMode}</td>
                             </tr>

                          </table>
                          <h3>Current State:</h3>
                          <table>
                             <tr>
                                <th>Attribute</th>
                                <th>Details</th>
                             </tr>
                             <tr>
                                <td>Pain While Swallowing</td>
                                <td>{convertToYesNo(patient.PatientCurrentStates.First().PainWhileSwallowing)}</td>
                             </tr>
                             <tr>
                                <td>Unable to Swallow Medication</td>
                                <td>{convertToYesNo(patient.PatientCurrentStates.First().UnableToSwallowTheMedication)}</td>
                             </tr>
                             <tr>
                                <td>Coughing/Choking while Eating</td>
                                <td>{convertToYesNo(patient.PatientCurrentStates.First().CoughingChokingWhileEating)}</td>
                             </tr>
                             <tr>
                                <td>Respiratory Distress while Eating</td>
                                <td>{convertToYesNo(patient.PatientCurrentStates.First().RespiratoryDistressWhileEating)}</td>
                             </tr>
                             <tr>
                                <td>Holding Food in Mouth for Long Time</td>
                                <td>{convertToYesNo(patient.PatientCurrentStates.First().HoldingFoodInMouthForLongTime)}</td>
                             </tr>
                             <tr>
                                <td>Drooling while Eating</td>
                                <td>{convertToYesNo(patient.PatientCurrentStates.First().DroolingWhileEating)}</td>
                             </tr>
                             <tr>
                                <td>Feeling Food Stuck in Throat</td>
                                <td>{convertToYesNo(patient.PatientCurrentStates.First().FeelingLikeFoodStuckedInThroat)}</td>
                             </tr>
                             <tr>
                                <td>Feeling Vomiting after Eating</td>
                                <td>{convertToYesNo(patient.PatientCurrentStates.First().FeelingVomitingAfterEating)}</td>
                             </tr>
                             <tr>
                                <td>Feeling Chest Burning after Eating</td>
                                <td>{convertToYesNo(patient.PatientCurrentStates.First().FeelingChestBurningAfterEating)}</td>
                             </tr>
                             <tr>
                                <td>Feeling Food Stuck in Chest</td>
                                <td>{convertToYesNo(patient.PatientCurrentStates.First().FeelingFoodStuckingInChest)}</td>
                             </tr>
                          </table>
                          <p>If you have any questions or need further information, please feel free to reach out.</p>
                          <p>Best regards,<br>[Your Name]</p>
                       </body>
                    </html>",
                    IsBodyHtml = true,
                };
                mailMessage.To.Add("28a.v10@gmail.com");//gnikhilaks@gmail.com
                smtpClient.Send(mailMessage);
                Console.WriteLine("Email sent successfully.");
                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }
    }
}

NationalDysphagiaCareGuid/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nation Dysphagia Connecting Guid</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NationalDysphagiaCareGuid.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100..900&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/14cff0f73f.js" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <style>
        body {
            font-family: "Montserrat", sans-serif;
            font-optical-sizing: auto;
            font-weight: <weight>;
            font-style: normal;
            background-image: linear-gradient(to top, #e6e9f0 0%, #eef1f5 100%);
        }

        header {
            left: 0;
            top: 0;
            width: 100%;
            position: fixed;
            z-index: 1000;
        }

        .lh-sm a {
            color: inherit; /* Use the default text color */
            text-decoration: none; /* Remove underline */
        }

        .lh-sm .social-link {
            display: block;
            margin-bottom: 8px; /* Adjust as needed */
        }

            .lh-sm .social-link i {
                margin-right: 8px; /* Adjust icon spacing */
            }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="rounded-circle d-inline-block align-text-top" src="~/img/NationalDysphagiaCareGuid_Logo3.png" alt="Logo" width="30" />
                    Nation Dysphagia Connecting Guid
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-house mx-2"></i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Form" asp-action="Index"><i class="fa-solid fa-rectangle-list mx-2"></i>User Form</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted position-relative">
        <div class="container p-sm-3">
            <div class="row">
                <div class="col-sm-6 col-md-6">
                    <h4 class="h4">About</h4>
                    <p class="lh-1" style="white-space:pre-wrap;">Welcome to Nation Dysphagia Connecting Guide, your trusted resource for understanding and managing dysphagia. We provide essential information about swallowing difficulties and offer a supportive community for patients and caregivers. Our goal is to empower individuals with personalized solutions and connect them with specialized healthcare professionals for comprehensive care.</p>
                </div>

                <div class="col-sm-3 col-md-3">
                    <h4 class="h4">Contact Us</h4>
                    <div class="lh-sm">
                        <div>
                            @* <p class="m-sm-0">123 Example Street</p> *@
                            <p class="m-sm-0"><i class="fa-solid fa-location-dot"></i> Gurugram, Haryana</p>
                        </div>
                        <div class="row p-sm-2"></div>
                        <p class="m-sm-0"><i class="fa-solid fa-at"></i> gnikhilaks@gmail.com</p>
                        <p class="m-sm-0"><i class="fa-solid fa-phone"></i> (+91) 958-2972-948</p>
                    </div>
                </div>

                @* <div class="col-sm-3 col-md-3">
                <!-- Logo in the second column -->
                <div class="text-center">
                <a asp-controller="Home" asp-action="Index">
                <img src="~/img/nationaldysphagiacareguid_logo.png" alt="Logo" style="max-width: 150px;" />
                </a>
                </div>
                </div> *@

                <div class="col-sm-3 col-md-3">
                    <h4 class="h4">Social</h4>
                    <div class="lh-sm">
                        <a class="social-link d-md-block" href="//api.whatsapp.com/send?phone=919582972948&text=HelloDoctor"><i class="fa-brands fa-whatsapp fa-lg mx-2"></i>Whatsapp</a>
                        <a class="social-link d-md-block"><i class="fa-brands fa-facebook fa-lg mx-2"></i>Facebook</a>
                        <a class="social-link d-md-block"><i class="fa-brands fa-instagram fa-lg mx-2"></i>Instagram</a>
                    </div>
                </div>
            </div>

            <!-- Copyright and Privacy section -->
            <div class="row mt-3">
                <div class="col">
                    &copy; 2024 - NationDysphagiaConnectingGuid - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </div>
        </div>
    </footer>
    @*     <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script> *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>